/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yazlab;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author ONUR
 */
public class GirisEkrani extends javax.swing.JFrame {

    static boolean check = true;
    static int x_ekseni;
    static  int y_ekseni;
    static int altinSayisi;
    static int adimSayisi;
    static int a_adim,b_adim,c_adim,d_adim;
    static int a_hedef,b_hedef,c_hedef,d_hedef;
    static int altin_koy, gizli_koy;
    
    public static int getA_adim() {
        return a_adim;
    }

    public static void setA_adim(int a_adim) {
        GirisEkrani.a_adim = a_adim;
    }

    public static int getB_adim() {
        return b_adim;
    }

    public static void setB_adim(int b_adim) {
        GirisEkrani.b_adim = b_adim;
    }

    public static int getC_adim() {
        return c_adim;
    }

    public static void setC_adim(int c_adim) {
        GirisEkrani.c_adim = c_adim;
    }

    public static int getD_adim() {
        return d_adim;
    }

    public static void setD_adim(int d_adim) {
        GirisEkrani.d_adim = d_adim;
    }

    public static int getA_hedef() {
        return a_hedef;
    }

    public static void setA_hedef(int a_hedef) {
        GirisEkrani.a_hedef = a_hedef;
    }

    public static int getB_hedef() {
        return b_hedef;
    }

    public static void setB_hedef(int b_hedef) {
        GirisEkrani.b_hedef = b_hedef;
    }

    public static int getC_hedef() {
        return c_hedef;
    }

    public static void setC_hedef(int c_hedef) {
        GirisEkrani.c_hedef = c_hedef;
    }

    public static int getD_hedef() {
        return d_hedef;
    }

    public static void setD_hedef(int d_hedef) {
        GirisEkrani.d_hedef = d_hedef;
    }

    public static int getAltin_koy() {
        return altin_koy;
    }

    public static void setAltin_koy(int altin_koy) {
        GirisEkrani.altin_koy = altin_koy;
    }

    public static int getGizli_koy() {
        return gizli_koy;
    }

    public static void setGizli_koy(int gizli_koy) {
        GirisEkrani.gizli_koy = gizli_koy;
    }
    public static int getX_ekseni() {
        return x_ekseni;
    }

    public static void setX_ekseni(int x_ekseni) {
        GirisEkrani.x_ekseni = x_ekseni;
    }

    public static int getY_ekseni() {
        return y_ekseni;
    }

    public static void setY_ekseni(int y_ekseni) {
        GirisEkrani.y_ekseni = y_ekseni;
    }

    public static int getAltinSayisi() {
        return altinSayisi;
    }

    public static void setAltinSayisi(int altinSayisi) {
        GirisEkrani.altinSayisi = altinSayisi;
    }

    public static int getAdimSayisi() {
        return adimSayisi;
    }

    public static void setAdimSayisi(int adimSayisi) {
        GirisEkrani.adimSayisi = adimSayisi;
    }

    public static boolean isCheck() {
        return check;
    }

    public static void setCheck(boolean check) {
        GirisEkrani.check = check;
    }
    public GirisEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        baslatma = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        baslangicAdim = new javax.swing.JTextField();
        yEkseni = new javax.swing.JTextField();
        baslangicAltin = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        a_hamlet = new javax.swing.JTextField();
        a_hedeft = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        xEkseni = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        b_hamlet = new javax.swing.JTextField();
        b_hedeft = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        c_hamlet = new javax.swing.JTextField();
        c_hedeft = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        d_hamlet = new javax.swing.JTextField();
        d_hedeft = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        altin_koyt = new javax.swing.JTextField();
        gizli_koyt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 650));

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        baslatma.setBackground(new java.awt.Color(255, 153, 0));
        baslatma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        baslatma.setText("                      BAŞLAT");
        baslatma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baslatmaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                baslatmaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                baslatmaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baslatma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baslatma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 280, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Haritadaki gizli altin sayisi (%):");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 210, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Boyut Y:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Baslangıç Altını:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 30));

        baslangicAdim.setBackground(new java.awt.Color(204, 204, 204));
        baslangicAdim.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        baslangicAdim.setText("3");
        baslangicAdim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baslangicAdimActionPerformed(evt);
            }
        });
        jPanel1.add(baslangicAdim, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 60, 30));

        yEkseni.setBackground(new java.awt.Color(204, 204, 204));
        yEkseni.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        yEkseni.setText("20");
        yEkseni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yEkseniActionPerformed(evt);
            }
        });
        jPanel1.add(yEkseni, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 60, 30));

        baslangicAltin.setBackground(new java.awt.Color(204, 204, 204));
        baslangicAltin.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        baslangicAltin.setText("200");
        baslangicAltin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baslangicAltinActionPerformed(evt);
            }
        });
        jPanel1.add(baslangicAltin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 60, 30));

        jPanel3.setBackground(new java.awt.Color(153, 255, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("    A");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Hedef Belirleme maaliyeti :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Hamle maliyeti:");

        a_hamlet.setBackground(new java.awt.Color(204, 204, 204));
        a_hamlet.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        a_hamlet.setText("5");
        a_hamlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_hamletActionPerformed(evt);
            }
        });

        a_hedeft.setBackground(new java.awt.Color(204, 204, 204));
        a_hedeft.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        a_hedeft.setText("5");
        a_hedeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_hedeftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a_hedeft, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_hamlet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(194, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(a_hamlet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_hedeft, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 310, 140));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Boyut X:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 30));

        xEkseni.setBackground(new java.awt.Color(204, 204, 204));
        xEkseni.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        xEkseni.setText("20");
        xEkseni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xEkseniActionPerformed(evt);
            }
        });
        jPanel1.add(xEkseni, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 60, 30));

        jPanel4.setBackground(new java.awt.Color(255, 204, 51));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("    B");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Hedef Belirleme maaliyeti :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Hamle maliyeti:");

        b_hamlet.setBackground(new java.awt.Color(204, 204, 204));
        b_hamlet.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_hamlet.setText("5");
        b_hamlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hamletActionPerformed(evt);
            }
        });

        b_hedeft.setBackground(new java.awt.Color(204, 204, 204));
        b_hedeft.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_hedeft.setText("10");
        b_hedeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hedeftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_hedeft, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_hamlet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_hamlet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_hedeft, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 310, -1));

        jPanel5.setBackground(new java.awt.Color(0, 255, 102));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("    C");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("Hedef Belirleme maaliyeti :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("Hamle maliyeti:");

        c_hamlet.setBackground(new java.awt.Color(204, 204, 204));
        c_hamlet.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        c_hamlet.setText("5");
        c_hamlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_hamletActionPerformed(evt);
            }
        });

        c_hedeft.setBackground(new java.awt.Color(204, 204, 204));
        c_hedeft.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        c_hedeft.setText("15");
        c_hedeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_hedeftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_hedeft, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_hamlet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_hamlet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_hedeft, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 310, -1));

        jPanel6.setBackground(new java.awt.Color(0, 153, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("    D");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("Hedef Belirleme maaliyeti :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setText("Hamle maliyeti:");

        d_hamlet.setBackground(new java.awt.Color(204, 204, 204));
        d_hamlet.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        d_hamlet.setText("5");
        d_hamlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_hamletActionPerformed(evt);
            }
        });

        d_hedeft.setBackground(new java.awt.Color(204, 204, 204));
        d_hedeft.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        d_hedeft.setText("20");
        d_hedeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_hedeftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d_hedeft, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_hamlet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_hamlet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_hedeft, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 310, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Adım Sayıs:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setText("Haritadaki altin sayisi (%):");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 180, 30));

        altin_koyt.setBackground(new java.awt.Color(204, 204, 204));
        altin_koyt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        altin_koyt.setText("20");
        altin_koyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altin_koytActionPerformed(evt);
            }
        });
        jPanel1.add(altin_koyt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 60, 30));

        gizli_koyt.setBackground(new java.awt.Color(204, 204, 204));
        gizli_koyt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        gizli_koyt.setText("10");
        gizli_koyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gizli_koytActionPerformed(evt);
            }
        });
        jPanel1.add(gizli_koyt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void baslatmaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baslatmaMouseEntered
        setColor(jPanel2);
    }//GEN-LAST:event_baslatmaMouseEntered

    private void baslatmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baslatmaMouseExited
        resetColor(jPanel2);
    }//GEN-LAST:event_baslatmaMouseExited

    private void baslatmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baslatmaMouseClicked
        x_ekseni = Integer.parseInt(xEkseni.getText());
        y_ekseni = Integer.parseInt(yEkseni.getText());
        altinSayisi = Integer.parseInt(baslangicAltin.getText());
        adimSayisi = Integer.parseInt(baslangicAdim.getText());
        a_adim = Integer.parseInt(a_hamlet.getText());
        b_adim = Integer.parseInt(b_hamlet.getText());
        c_adim = Integer.parseInt(c_hamlet.getText());
        d_adim = Integer.parseInt(d_hamlet.getText());
        a_hedef = Integer.parseInt(a_hedeft.getText());
        b_hedef = Integer.parseInt(b_hedeft.getText());
        c_hedef = Integer.parseInt(c_hedeft.getText());
        d_hedef = Integer.parseInt(d_hedeft.getText());
        altin_koy = Integer.parseInt(altin_koyt.getText());
        gizli_koy = Integer.parseInt(gizli_koyt.getText());



        this.setVisible(false);
        check = false;
    }//GEN-LAST:event_baslatmaMouseClicked

    private void baslangicAdimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baslangicAdimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baslangicAdimActionPerformed

    private void a_hamletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_hamletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_hamletActionPerformed

    private void yEkseniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yEkseniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yEkseniActionPerformed

    private void baslangicAltinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baslangicAltinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baslangicAltinActionPerformed

    private void xEkseniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xEkseniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xEkseniActionPerformed

    private void a_hedeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_hedeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_hedeftActionPerformed

    private void b_hamletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hamletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_hamletActionPerformed

    private void b_hedeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hedeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_hedeftActionPerformed

    private void c_hamletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_hamletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_hamletActionPerformed

    private void c_hedeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_hedeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_hedeftActionPerformed

    private void d_hamletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_hamletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_hamletActionPerformed

    private void d_hedeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_hedeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_hedeftActionPerformed

    private void altin_koytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altin_koytActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_altin_koytActionPerformed

    private void gizli_koytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gizli_koytActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gizli_koytActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a_hamlet;
    private javax.swing.JTextField a_hedeft;
    private javax.swing.JTextField altin_koyt;
    private javax.swing.JTextField b_hamlet;
    private javax.swing.JTextField b_hedeft;
    private javax.swing.JTextField baslangicAdim;
    private javax.swing.JTextField baslangicAltin;
    private javax.swing.JLabel baslatma;
    private javax.swing.JTextField c_hamlet;
    private javax.swing.JTextField c_hedeft;
    private javax.swing.JTextField d_hamlet;
    private javax.swing.JTextField d_hedeft;
    private javax.swing.JTextField gizli_koyt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField xEkseni;
    private javax.swing.JTextField yEkseni;
    // End of variables declaration//GEN-END:variables

    public void setColor(JPanel panel){
        panel.setBackground(new Color(255,105,0));
    }
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(255,153,0));
    }
}
